### ISSUE TITLE
Error when opening dialogs

### ISSUE THREAD

**Issue by dkkost** [DualSPHysics/DesignSPHysics#230]
I installed DesignSPHysics using the Freecad addon manager and am able to start the script and create a new case. But when I click on "Execution Parameters" or "Define Constants" I get an error message:

DesignSPHysics version: 0.7.1 (25-11-2024)
Platform: Windows-10-10.0.19045
FreeCAD Version: 1.0.0
Exception type: <class 'AttributeError'>
Exception value: module 'PySide2.QtWidgets' has no attribute 'QIntValidator'
Traceback:

  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\dock\dock_configuration_widget.py", line 85, in on_execparams_button_presed
    ExecutionParametersDialog(parent=get_fc_main_window())
  File "C:\Users\user\AppData\Roaming\FreeCAD\Mod\DesignSPHysics\mod\widgets\execution_parameters_dialog.py", line 89, in __init__
    self.verletsteps_validator = QtWidgets.QIntValidator(0, 9999, self.verletsteps_input)
                                 ^^^^^^^^^^^^^^^^^^^^^^^

I use Freecad 1.0 but the same error occurs with 0.21.2 as well.

**Comment by imestevez** [comment]
This issue was fixed yesterday in the latest commit. Please, download and try again

**Comment by 258458** [comment]
![image](https://github.com/user-attachments/assets/bc241738-e0cd-46a8-a64d-b2bf49ac05b4)

**Comment by 258458** [comment]
When I open it, the left settings box doesn't show up, and the uninstall and reinstall still doesn't change

**Comment by imestevez** [comment]
@dkkost Please try again. Some of the new dependencies for FreeCAD v1.0 have not been updated and should work now.

**Comment by 258458** [comment]
ok，thank you

**Comment by dkkost** [comment]
> @dkkost Please try again. Some of the new dependencies for FreeCAD v1.0 have not been updated and should work now.

The dialogs work now, thanks!

**Comment by 258458** [comment]
I would like to ask, is there any way to convert the SPH interface to Chinese？

**Comment by imestevez** [comment]
No, the GUI is only developed in English.

**Comment by 258458** [comment]
![Uploading 微信截图_20241129105144.png…]()

**Comment by 258458** [comment]
![image](https://github.com/user-attachments/assets/870ef7de-30af-4531-8528-d768a7f812d5)

**Comment by 258458** [comment]
I would like to ask what is the reason for this?

**Comment by imestevez** [comment]
The same issue is discussed here: https://github.com/DualSPHysics/DesignSPHysics/issues/228
