### ISSUE TITLE
inlet/outlet problem

### ISSUE THREAD

**Issue by jeanefachi88** [DualSPHysics/DesignSPHysics#50]
Hello,  

I’m new to DualSPHysics and want to simulate Wave with velocity and elevation. 
I’ve tried to do this in Special > Inlet/Outlet. 
But, everytime I've tried to apply some fixed velocity or elevation value, it appears this error:  

*** Exception (JXml::ErrReadAtrib) 

Text: Error reading xml - Value of 'reuseids' invalid. 

File: C:/Users/jeane.fachi/Documents/Intership/Cases/QQtestes/QQtestes_out/QQtestes.xml(row:100) 
Finished execution (code=1). 

What would you suggest?

**Comment by zlotny** [comment]
Hi there, thanks for submitting the issue.

The reuseids option is not yet supported by DualSPHysics and it slipped out in a DesignSPHysics release in testing. Please, set it to false.

Then I recommend you to update your DesignSPHysics version (Addons -> Addon Manager -> Select DesignSPHysics -> Install/Update)

This was already brought up and solved in #35 

I hope that helps.

**Comment by jeanefachi88** [comment]
Thanks zlotny. 

I already updated the DesignSPHysics yesterday and tried to do this, but still not working. 
I'll wait for this upgrade. 

Thanks a lot.

**Comment by zlotny** [comment]
You're absolutely right. Someway I messed up while fixing the #35 issue and reuseids basically defaulted to True. 

Somehow the user that opened that issue didn't complain about it. It is fixed now on master. Please update DesignSPHysics to the latest version and check again if everything goes correctly.

Thanks for noticing that, I thought it was already solved!

**Comment by jeanefachi88** [comment]
Hi, I updated the DesignSPHysics to 0.6.0.2001-30-2 version and tried to run again. 
I put constante velocity = 0.1m/s and still appears the following message:


*** Exception (JSphGpuSingle::LoadCaseConfig)
Text: Inlet/Outlet with ReuseIds is not a valid option for now...

If you want to verify, the case is attached bellow. 

[QQtestes.zip](https://github.com/DualSPHysics/DesignSPHysics/files/4139014/QQtestes.zip)

Best regards.

**Comment by zlotny** [comment]
Hi there,

There was a lot of changes in Inlet/Outlet on DualSPHysics, so a coworker suggested me to update the version. I made this change alongside other that were needed to make it work, so the configuration changed a bit.

Please update your DesignSPHysics version and try to update your Inlet/Outlet conditions. However, by words of a coworker, Inlet/Oulet is definitely not ready to use via the GUI right now, and I'm afraid I don't quite understand all of the new options for it in DualSPHysics.

I'll try to update DesignSPHysics with the new options on the interface when I have time.

**Comment by zlotny** [comment]
Inlet/Outlet is now ready to use with the new opcions as of commit bf17b3b7da78efbc3de37c716d3c47e844bf08da in develop.

Closing this as it is now in a different state and for lack of activity
