### ISSUE TITLE
Error in "uniformly accelerated rectilinear motion"

### ISSUE THREAD

**Issue by Scientifix97** [DualSPHysics/DesignSPHysics#71]
Hello,
I am using DesignSPHysic's latest macro on freeCAD and I have the following issue : 
When adding a "uniformly accelerated rectilinear motion" to my solid an error appears in the xml file.
![Capture2](https://user-images.githubusercontent.com/63786988/79451708-416c2200-7fe7-11ea-885f-c319bc1b7c01.PNG)
It should be : duration="1" next="1"
Moreover I cannot choose the initial velocity and acceleration field from DesignSPHysics. I only have 3 boxes which setup the initial velocity components but nothing to set the acceleration field. Modifying the XML file manually and trying to start the simulation using the corrected file doesn't work as the XML is overwritten....
Hope you can fix this !!
Thanks a lot,
Scientifix97

**Comment by zlotny** [comment]
Hi there, thanks for reporting the issue! It should be fixed now on the master branch so you can update DesignSPHysics via de Addon Manager and it should save the XML correctly.

The commit that fixed that is: f558b80d35d8145eb139cb6e238aff40bd09a396

About not having all the options: DesignSPHysics is a tool intended to get people to learn a bit about DualSPHysics in an easy way, but not as a replacement, so we support basic features to get people started and then continue on the XML workflow, as the DualSPHyiscs suite has multiple developers and contributors vs. this, which has only myself :)

Maybe in the future when DesignSPHysics is feature complete in other aspects with more priority to the team we'll include all the options in each motion, but for now we recommend people that want to simulate more advanced cases to use the command line tools.

A quick way to do that is just to run GenCase and check de details once it's finished ; There you should see the command that was executed to run GenCase, which you can copy, tweak and execute later. You can also do that with Run, so you can check how the command line looks like and use it as an starting point.

Using the GUI everytime an user runs GenCase the case gets saved and the XML is generated again, to ensure all the latest changes are saved to disk before running the tool, so if you want to tweak the XML yourself you'll have to use DualSPHysics in command line.

I'm closing this as the issue should be fixed now. Thanks for using DesignSPHysics!

**Comment by Scientifix97** [comment]
Thanks a lot, the XML file is now correctly generated !!
The second issue that I mentionned is not fixed tho, choosing the "uniformly accelerated rectilinear motion" does not permit to create a "uniformly accelerated rectilinear motion" in DesignSPHysics as the boxes to input the acceleration are missing !!
![Capture3](https://user-images.githubusercontent.com/63786988/79455862-d07c3880-7fed-11ea-9f08-342fa1e34f36.PNG)
Thanks again for the quick answer !!
Best,
Scientifix

**Comment by zlotny** [comment]
Oh, sorry about that. I was looking to a lot of things and I mixed them, so I misunderstood. Sorry! :sweat_smile: 

I'll take a look to the GUI, indeed those  boxes are missing.

PS: I was reading a mail asking for X feature that we don't support right now, that's why I mixed it. Sorry!

**Comment by zlotny** [comment]
Done, it should be alright now. Sorry about that. Closing the issue! Thanks for the patience!

**Comment by rambisneves** [comment]
Good morning, I'm start to learn a freecad+dualphysics, how did stayed xml with rotation in impeler for example?
